// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8tfZ7_wCBhN2QFlGhU0ViHoGY6oyPVUE',
    appId: '1:1036682341839:web:15328a120efffc2a2536ba',
    messagingSenderId: '1036682341839',
    projectId: 'quiz-app-42027',
    authDomain: 'quiz-app-42027.firebaseapp.com',
    storageBucket: 'quiz-app-42027.appspot.com',
    measurementId: 'G-RPF5VWLYBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLP5tI_DjVK9eW4FmjugjvIHDRygA3zDY',
    appId: '1:1036682341839:android:66bc8f02d7aec7da2536ba',
    messagingSenderId: '1036682341839',
    projectId: 'quiz-app-42027',
    storageBucket: 'quiz-app-42027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPTXhQRhspRfSvqpCqEk0jY-OcnLte30s',
    appId: '1:1036682341839:ios:b7860eb07ab9fe1f2536ba',
    messagingSenderId: '1036682341839',
    projectId: 'quiz-app-42027',
    storageBucket: 'quiz-app-42027.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPTXhQRhspRfSvqpCqEk0jY-OcnLte30s',
    appId: '1:1036682341839:ios:b6a79475d0f5dc452536ba',
    messagingSenderId: '1036682341839',
    projectId: 'quiz-app-42027',
    storageBucket: 'quiz-app-42027.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
